language: c++

compiler:
 - gcc
 - clang

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:
 - pwd
 - CHECKOUTFOLDER=`pwd`
 - cd
 - sudo apt-get install libgtest-dev
 - git clone https://github.com/google/benchmark.git gbench
 - cd gbench
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
 - make 
 - sudo make install
 - cd

script: 
 - cd $CHECKOUTFOLDER
 - cd ..
 - mkdir build
 - cd build
 - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ../QuickType 
 - cmake --build . -- -j2

