language: c++

compiler:
 - gcc
 - clang

group: stable
os: linux
dist: artful

install:
 - pwd
 - CHECKOUTFOLDER=`pwd`
 - cd
 - sudo apt-get install libgtest-dev
 - sudo apt-get install cmake-extras
 - git clone https://github.com/google/benchmark.git gbench
 - cd gbench
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
 - make 
 - sudo make install
 - cd

script: 
 - cd $CHECKOUTFOLDER
 - cd ..
 - mkdir build
 - cd build
 - cmake ../QuickType 
 - make

