language: c++

sudo: required

services:
 - docker

before_install:
 - export FOLDER=`pwd`
 - echo $FOLDER
 - cd docker
 - docker build -t buildimg .

compiler:
 - gcc
 - clang
 
script: 
 - echo $FOLDER
 - docker run -t -v $FOLDER:/root/QuickType -e CXX=$CXX -e CC=$CC buildimg /root/build_script.sh

