language: c++

sudo: required

services:
 - docker

before_install:
 - export FOLDER=`pwd`
 - echo $FOLDER
 - cd docker
 - docker build -t buildimg .

 
script: 
 - echo $FOLDER
 - docker run -t -v $FOLDER:/root/QuickType buildimg /root/build_script.sh

