language: c++

install:
 - sudo apt-get install libgtest-dev
 - git clone https://github.com/google/benchmark.git gbench
 - cd gbench
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
 - make 
 - sudo make install
 - cd

script: 
 - cd .. 
 - mkdir build
 - cd build
 - cmake ../QuickType 
 - make

compiler:
 - gcc
 - clang
