language: c++

sudo: required

services:
 - docker

before_install:
 - cd docker
 - docker build -t buildimg .

 
script: 
 - cd
 - docker run -t -v `pwd`/michaelzs85/QuickType:/root/QuickType buildimg /root/build_script.sh

